# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files

  - repo: https://github.com/compilerla/conventional-pre-commit
    rev: v2.2.0
    hooks:
      - id: conventional-pre-commit
        stages: [ commit-msg ]
        args: [ feat, fix, ci, chore, test ]

  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.0.292
    hooks:
      - id: ruff

  - repo: https://github.com/ambv/black
    rev: 23.3.0
    hooks:
      - id: black
        args: [ --config=./pyproject.toml ]
        exclude: migrations

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.3.0
    hooks:
      - id: mypy
        args: [ --config-file=pyproject.toml ]
        exclude: migrations
