version: "3.10"

services:
  user_service:
    build:
      context: .
      dockerfile: ./microservices/user_service/Dockerfile
    depends_on:
        - postgres
    volumes:
      - ./microservices/user_service:/app
      - ./microservices/user_service/alembic:/app/alembic
    env_file:
      - ./.env.example
  postgres:
    image: "postgres:15.1"
    command: ["postgres", "-c", "log_statement=all"]
    ports:
      - "5432:5432"
    healthcheck:
      test: pg_isready -U orders_service_local
      timeout: 20s
      retries: 3
    environment:
      POSTGRES_DB: "postgres"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data: