version: "3.10"

services:
  user_service:
    build:
      context: .
      dockerfile: ./microservices/user_service/Dockerfile
    volumes:
      - ./microservices/user_service:/app
      - ./microservices/user_service/alembic:/app/alembic
    env_file:
      - ./.env.example
    command: uvicorn main:make_app --factory --host 0.0.0.0 --port 8080 --reload
    depends_on:
      - postgres

  postgres:
    image: "postgres:15.1"
    command: ["postgres", "-c", "log_statement=all"]
    ports:
      - "5432:5432"
    healthcheck:
      test: pg_isready -U postgres
      timeout: 20s
      retries: 3
    env_file:
      - ./.env.example
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
