version: "3.10"

x-base-user-service: &base-user-service
  build:
    context: .
    dockerfile: ./microservices/user_service/Dockerfile
  volumes:
    - ./microservices/user_service:/app
    - ./microservices/user_service/alembic:/app/alembic


services:
  user_service:
    <<: *base-user-service
    env_file:
      - ./.env.example
    command: uvicorn main:make_app --factory --host 0.0.0.0 --port 8080 --reload
    ports:
      - "8080:8080"
    depends_on:
      - postgres
      - rabbitmq

  user_service_publisher:
    <<: *base-user-service
    command: sh -c "sleep 10 && python publisher.py"
    depends_on:
      - postgres
      - rabbitmq

  user_service_consumer:
    <<: *base-user-service
    command: sh -c "sleep 10 && python consumer.py"
    depends_on:
      - postgres
      - rabbitmq

  postgres:
    image: "postgres:15.1"
    command: ["postgres", "-c", "log_statement=all"]
    ports:
      - "5432:5432"
    healthcheck:
      test: pg_isready -U postgres
      timeout: 20s
      retries: 3
    env_file:
      - ./.env.example
    volumes:
      - postgres-data:/var/lib/postgresql/data

  rabbitmq:
    image: "rabbitmq:3.12.7-management"
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    volumes:
      - rabbit-data:/var/lib/rabbitmq/

volumes:
  postgres-data:
  rabbit-data:
