version: "3.10"

x-base-user-service: &base-user-service
  build:
    context: .
    dockerfile: ./microservices/user_service/Dockerfile
  volumes:
    - ./microservices/user_service:/app
    - ./microservices/user_service/alembic:/app/alembic
  env_file:
    - .env.postgres.example
  depends_on:
    - postgres
    - rabbitmq


services:
  user_service:
    <<: *base-user-service
    command: uvicorn main:make_app --factory --host 0.0.0.0 --port 8080 --reload
    ports:
      - "8080:8080"

  user_service_publisher:
    <<: *base-user-service
    command: python publisher.py
    env_file:
      - .env.postgres.example
      - .env.rabbitmq.example
    depends_on:
      postgres:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy

  user_service_consumer:
    <<: *base-user-service
    command: python consumer.py
    env_file:
      - .env.postgres.example
      - .env.rabbitmq.example
    depends_on:
      postgres:
          condition: service_healthy
      rabbitmq:
          condition: service_healthy

  reverse_service:
    build:
      context: .
      dockerfile: ./microservices/reverse_service/Dockerfile
    volumes:
      - ./microservices/reverse_service:/app
    command: python main.py
    env_file:
      - .env.rabbitmq.example
    depends_on:
      rabbitmq:
        condition: service_healthy

  postgres:
    image: "postgres:15.1"
    command: ["postgres", "-c", "log_statement=all"]
    ports:
      - "5432:5432"
    healthcheck:
      test: pg_isready -U postgres
      timeout: 5s
      retries: 5
    env_file:
      - .env.postgres.example
    volumes:
      - postgres-data:/var/lib/postgresql/data

  rabbitmq:
    image: "rabbitmq:3.12.7-management"
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: rabbitmq-diagnostics check_port_connectivity
      timeout: 5s
      retries: 5
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    volumes:
      - rabbit-data:/var/lib/rabbitmq/

volumes:
  postgres-data:
  rabbit-data:
